# Generated by Django 5.0.6 on 2026-06-21 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_date', models.DateTimeField()),
                ('delivery_type', models.CharField(max_length=255)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('audio', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('meal_prep', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.address')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('assurance_at', models.DateTimeField(blank=True, null=True)),
                ('pass_quality_assurance', models.BooleanField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('re_assigned', models.BooleanField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendor_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commision', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referral', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('assurance_user', models.ForeignKey(blank=True, db_column='assurance_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_order_items', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(blank=True, db_column='ingredient_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.ingredient')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.product')),
                ('referral_user', models.ForeignKey(blank=True, db_column='referral_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_order_items', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_order_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('processing', 'processing'), ('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled')], max_length=20)),
                ('changed_at', models.DateTimeField()),
                ('order_item', models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.orderitem')),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_item_logs',
            },
        ),
    ]
