# Generated by Django 5.0.6 on 2026-07-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemlog',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('processing', 'processing'), ('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled'), ('rejected', 'rejected')], max_length=20),
        ),
    ]
