# Generated by Django 5.0.6 on 2026-07-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitemlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemlog',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('processing', 'processing'), ('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled'), ('rejected', 'rejected'), ('delivered', 'delivered')], max_length=20),
        ),
    ]
