# Generated by Django 5.0.6 on 2026-07-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitemlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOfferResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('decision', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'market_offer_responses',
            },
        ),
        migrations.CreateModel(
            name='OrderItemMarketAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('offered', 'offered'), ('accepted', 'accepted'), ('escalated_timeout', 'escalated_timeout'), ('escalated_all_declined', 'escalated_all_declined'), ('escalated_no_vendor', 'escalated_no_vendor')], default='offered', max_length=30)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_item_market_attempts',
            },
        ),
    ]
