# Generated by Django 5.0.6 on 2026-07-31 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_marketofferresponse_orderitemmarketattempt'),
        ('vendors', '0003_market_vendor_market'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='market',
            field=models.ForeignKey(blank=True, db_column='market_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='vendors.market'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketofferresponse',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitemmarketattempt',
            name='market',
            field=models.ForeignKey(db_column='market_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_attempts', to='vendors.market'),
        ),
        migrations.AddField(
            model_name='orderitemmarketattempt',
            name='order_item',
            field=models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='market_attempts', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='marketofferresponse',
            name='attempt',
            field=models.ForeignKey(db_column='attempt_id', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='orders.orderitemmarketattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='marketofferresponse',
            unique_together={('attempt', 'vendor')},
        ),
    ]
