# Generated by Django 5.0.6 on 2026-08-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_market_orderitem_offer_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_dispatch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitemlog',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('processing', 'processing'), ('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled'), ('rejected', 'rejected'), ('delivered', 'delivered'), ('delivery_timeout', 'delivery_timeout')], max_length=20),
        ),
    ]
