# Generated by Django 5.0.6 on 2026-09-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='replace_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
