# Generated by Django 5.0.6 on 2026-07-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fcmdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('super_admin', 'Super Admin'), ('state_admin', 'State Admin'), ('vendor_manager', 'Vendor Manager'), ('accounts', 'Accounts'), ('audit', 'Audit'), ('logistics', 'Logistics'), ('vendor', 'Vendor'), ('customer', 'Customer'), ('qa', 'Quality Assurance'), ('account', 'Account'), ('state_representative', 'State Representative')], default='customer', max_length=255),
        ),
    ]
