# Generated by Django 5.0.6 on 2026-06-21 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('owner_type', models.CharField(max_length=255)),
                ('owner_id', models.BigIntegerField()),
                ('bank_code', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'commissions',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('txn_ref', models.CharField(db_index=True, max_length=255, unique=True)),
                ('authorization_url', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('gateway_response', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('transaction_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_owner_id', models.BigIntegerField(blank=True, null=True)),
                ('transaction_owner_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_initiator_id', models.BigIntegerField(blank=True, null=True)),
                ('transaction_initiator_type', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'payment_logs',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reference', models.CharField(max_length=255)),
                ('recipient_code', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('owner_type', models.CharField(max_length=255)),
                ('owner_id', models.BigIntegerField()),
                ('bank_code', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('failures', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='PaymentNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('account_owner_type', models.CharField(max_length=255)),
                ('account_owner_id', models.BigIntegerField()),
                ('owner_type', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_id', models.BigIntegerField(blank=True, null=True)),
                ('reference', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('old_balance', models.FloatField()),
                ('new_balance', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('is_refund', models.BooleanField(default=False)),
                ('has_refund', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('wallet', models.ForeignKey(blank=True, db_column='wallet_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.wallet')),
            ],
            options={
                'db_table': 'transaction_logs',
            },
        ),
    ]
