# Generated by Django 5.0.6 on 2026-08-13 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_seed_service_fee_tiers'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lga', models.ForeignKey(blank=True, db_column='lga_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fees', to='geo.lga')),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fees', to='geo.state')),
            ],
            options={
                'db_table': 'delivery_fees',
                'unique_together': {('state', 'lga')},
            },
        ),
    ]
