# Generated by Django 5.0.6 on 2026-08-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product_is_active'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='IngredientLgaSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, related_name='lga_suspensions', to='catalogue.ingredient')),
                ('lga', models.ForeignKey(db_column='lga_id', on_delete=django.db.models.deletion.CASCADE, to='geo.lga')),
            ],
            options={
                'db_table': 'ingredient_lga_suspensions',
                'unique_together': {('ingredient', 'lga')},
            },
        ),
        migrations.CreateModel(
            name='IngredientStateSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, related_name='state_suspensions', to='catalogue.ingredient')),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='geo.state')),
            ],
            options={
                'db_table': 'ingredient_state_suspensions',
                'unique_together': {('ingredient', 'state')},
            },
        ),
        migrations.CreateModel(
            name='ProductLgaSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lga', models.ForeignKey(db_column='lga_id', on_delete=django.db.models.deletion.CASCADE, to='geo.lga')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='lga_suspensions', to='catalogue.product')),
            ],
            options={
                'db_table': 'product_lga_suspensions',
                'unique_together': {('product', 'lga')},
            },
        ),
        migrations.CreateModel(
            name='ProductStateSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='state_suspensions', to='catalogue.product')),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='geo.state')),
            ],
            options={
                'db_table': 'product_state_suspensions',
                'unique_together': {('product', 'state')},
            },
        ),
    ]
