# Generated by Django 5.0.6 on 2026-08-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_ingredientproduct_price'),
        ('vendors', '0003_market_vendor_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientMarketSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, related_name='market_suspensions', to='catalogue.ingredient')),
                ('market', models.ForeignKey(db_column='market_id', on_delete=django.db.models.deletion.CASCADE, to='vendors.market')),
            ],
            options={
                'db_table': 'ingredient_market_suspensions',
                'unique_together': {('ingredient', 'market')},
            },
        ),
        migrations.CreateModel(
            name='ProductMarketSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('market', models.ForeignKey(db_column='market_id', on_delete=django.db.models.deletion.CASCADE, to='vendors.market')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='market_suspensions', to='catalogue.product')),
            ],
            options={
                'db_table': 'product_market_suspensions',
                'unique_together': {('product', 'market')},
            },
        ),
    ]
