# Generated by Django 5.0.6 on 2026-08-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_ingredientmarketsuspension_productmarketsuspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
