# Generated by Django 5.0.6 on 2026-07-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staterepresentative',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staterepresentative',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staterepresentative',
            name='lga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staterepresentative',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
