# Generated by Django 5.0.6 on 2026-07-31 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('vendors', '0002_state_representative_richer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('lga', models.ForeignKey(blank=True, db_column='lga_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markets', to='geo.lga')),
                ('state', models.ForeignKey(blank=True, db_column='state_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markets', to='geo.state')),
            ],
            options={
                'db_table': 'markets',
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='market',
            field=models.ForeignKey(blank=True, db_column='market_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendors.market'),
        ),
    ]
